### ISSUE TITLE
The button function doesn't work properly

### ISSUE THREAD

**Issue by Bammcool2011** [NayHtetKyaw/frieren-forever#5]
Hello America ya!

I just try to add `hover` and link components. but it doesn't work properly please help!

![image](https://github.com/NayHtetKyaw/frieren-forever/assets/22913542/687b9567-e94a-4ca7-a6ae-e565c0c36654)

**Comment by Long104** [comment]
i don't know too

**Comment by Bammcool2011** [comment]
I found it. The image of  hero's party is large (fit to the screen) please crop or resize it.

**Comment by Bammcool2011** [comment]
FIXED
